image: node:latest
stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules
            - package-lock.json
        #expire_in: 1 week 

deploy:
    stage: deploy
    script:
        - node server.js  > /dev/null 2>&1 &
