image: node:latest
stages:
    - build
    - deploy

build:
    stage: build
    script:
        - apt update -y
        - apt install npm -y
        - npm install

deploy:
    stage: deploy
    script:
        - apt update -y
        - apt install nodejs -y
        - node server.js
