stages:
    - build_stage
    - deploy_stage

build:
    stage: build_stage
    script:
        - docker --version
        - docker build -t nodeapp . # build image using docker file in same directory with name nodeapp
    tags:
        - localshell # tag local runner
        - localrunner # tag local runner

deploy:
    stage: deploy_stage
    script:
        - docker stop nodeappcontainer || true && docker rm nodeappcontainer || true
        - docker run -d --name nodeappcontainer -p 3000:8080 nodeapp
    tags:
        - localshell
        - localrunner
